### ISSUE TITLE
需要精确算法的实验数据集 需要精确算法的实验数据集 Experimental data sets requiring precise algorithms

### ISSUE THREAD

**Issue by name123-cheng** [JavaZakariae/MinDominatingSet#8]
Where is the data set of precise algorithm? Could you please send me one?

**Comment by JavaZakariae** [comment]
Ok, I need some time to check that.

**Comment by name123-cheng** [comment]
Thank you very much. I'm also doing research in this area. I need your data set to do experiments.

**Comment by name123-cheng** [comment]
Excuse me, have you found the data set of this precise algorithm?

**Comment by JavaZakariae** [comment]
They are located [here](https://github.com/JavaZakariae/MinDominatingSet/tree/master/src/main/resources): 
every folder contains one type of graph, there is an info text file that describes that type of graph.
you should also read the readme section to understand more.
